### ISSUE TITLE
Would you consider submitting a pull request to rspec-expecations?

### ISSUE THREAD

**Issue by aaronrenner** [sleepingkingstudios/rspec-sleeping_king_studios#12]
I just ran across your enhanced respond_to matcher and really like that it has keyword support. Would you consider submitting a pull request to the rspec project, so everyone can benefit from your enhancements without having to know about this gem?

**Comment by sleepingkingstudios** [comment]
The reason I haven't done so in the past is because of support for previous Ruby versions. `RSpec::SleepingKingStudios` explicitly only supports Ruby 2.0 and above, and it still requires version checks in some of the code to support required keyword arguments. Plus, I don't exactly get a tonne of feedback, so it's hard to judge how useful these features are to other developers. That being said, I'm willing to get in touch and see if any of my work would be valuable to the core project.

Also, if you do not mind my asking, how did you run across my work?

**Comment by aaronrenner** [comment]
I ran across your work when I was searching for an rspec `#respond_to` matcher that had keyword support. It was exactly what I was looking for, and I really appreciate your work. I'm excited to explore your other matchers too.

**Comment by sleepingkingstudios** [comment]
https://github.com/rspec/rspec-expectations/blob/master/Changelog.md#350--2016-07-01

**Comment by aaronrenner** [comment]
Awesome! Thank you! 👍
